# Generated by Django 5.2.1 on 2026-04-12 16:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('is_working_day', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('rescheduled', 'Перенесена'), ('no_show', 'Неявка')], default='created', max_length=20)),
                ('source', models.CharField(choices=[('master_manual', 'Создана мастером'), ('public_booking', 'Публичная запись')], default='master_manual', max_length=20)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('planned_duration_min', models.PositiveIntegerField()),
                ('planned_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment_client', models.TextField(blank=True, null=True)),
                ('comment_master', models.TextField(blank=True, null=True)),
                ('needs_removal', models.BooleanField(default=False)),
                ('needs_strengthening', models.BooleanField(default=False)),
                ('design_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='appointment_end_after_start')],
            },
        ),
    ]
